sonar.organization=loerei
sonar.projectKey=loerei_Auto-Mudae
sonar.projectName=Auto Mudae

sonar.sources=backend/src,frontend/src
sonar.tests=tests
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/__pycache__/**,tests/**,frontend/node_modules/**
sonar.cpd.exclusions=tests/**
sonar.coverage.exclusions=**/*
